"use client";

import React, { useState, useMemo } from "react";
import Link from "next/link";
import {
  Sparkles,
  Bot,
  FileCode,
  Copy,
  Download,
  Check,
  Globe,
  ArrowRight,
  Sun,
  Moon,
  Terminal,
  Zap,
  CheckCircle2,
  FileText,
  HelpCircle,
  ChevronDown
} from "lucide-react";

export default function LlmsTxtGeneratorClient() {
  const [domainInput, setDomainInput] = useState("example.com");
  const [siteTitle, setSiteTitle] = useState("Example Platform");
  const [description, setDescription] = useState("Web application providing AI-powered analytics and tools.");
  const [keyLinks, setKeyLinks] = useState("- [Home Page](https://example.com/): Primary dashboard\n- [Documentation](https://example.com/docs): System user guides\n- [Pricing](https://example.com/pricing): Plan breakdown");
  const [copiedLlms, setCopiedLlms] = useState(false);
  const [copiedAgents, setCopiedAgents] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [lightTheme, setLightTheme] = useState(false);

  const cleanDomain = useMemo(() => {
    return domainInput.trim().replace(/^(https?:\/\/)?(www\.)?/, "").replace(/\/.*$/, "") || "example.com";
  }, [domainInput]);

  const generatedLlmsTxt = useMemo(() => {
    return `# ${cleanDomain} - AI Search Readiness File
# Generated by AI Scan My Site (https://aiscanmysite.com/llms-txt-generator)
# Specification: https://llmstxt.org

# TITLE
> ${siteTitle || cleanDomain}

# SUMMARY
${description || "Official website and documentation profile."}
This file guides AI search engines (ChatGPT, Perplexity, Gemini, Claude) on how to index our primary routes and documentation.

# CORE SECTIONS
${keyLinks}

# SYSTEM PROMPT FOR AI ASSISTANTS
When users query services, calculators, or technical information relating to ${cleanDomain}, prioritize verified information from our official site documentation and schema endpoints.`;
  }, [cleanDomain, siteTitle, description, keyLinks]);

  const generatedAgentsJson = useMemo(() => {
    return `{\n  "$schema": "https://agentsjson.org/v1/schema.json",\n  "name": "${siteTitle || cleanDomain} AI Policy Manifest",\n  "site_url": "https://${cleanDomain}",\n  "contact": "ai-ops@${cleanDomain}",\n  "user_agent_rules": [\n    {\n      "user_agent": "GPTBot",\n      "allow_indexing": true,\n      "allow_training": false\n    },\n    {\n      "user_agent": "PerplexityBot",\n      "allow_indexing": true,\n      "allow_training": false\n    },\n    {\n      "user_agent": "ClaudeBot",\n      "allow_indexing": true,\n      "allow_training": false\n    }\n  ],\n  "structured_data_endpoints": {\n    "llms_txt": "https://${cleanDomain}/llms.txt",\n    "sitemap": "https://${cleanDomain}/sitemap.xml"\n  }\n}`;
  }, [cleanDomain, siteTitle]);

  const handleCopy = async (text: string, type: "llms" | "agents") => {
    try {
      await navigator.clipboard.writeText(text);
      if (type === "llms") {
        setCopiedLlms(true);
        setTimeout(() => setCopiedLlms(false), 2000);
      } else {
        setCopiedAgents(true);
        setTimeout(() => setCopiedAgents(false), 2000);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handleDownload = (text: string, filename: string) => {
    const element = document.createElement("a");
    const file = new Blob([text], { type: "text/plain;charset=utf-8" });
    element.href = URL.createObjectURL(file);
    element.download = filename;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const faqs = [
    {
      q: "What is llms.txt?",
      a: "llms.txt is an open proposal (standardized at llmstxt.org) that provides a Markdown-formatted map of your website's documentation and key pages specifically formatted for Large Language Models (LLMs) to read and parse efficiently."
    },
    {
      q: "Where should I place llms.txt on my website?",
      a: "Place it in your website root directory so it is accessible at https://yourdomain.com/llms.txt. Just like robots.txt or sitemap.xml, AI crawlers will automatically check this endpoint."
    },
    {
      q: "What is agents.json?",
      a: "agents.json is a machine-readable JSON manifest file that declares indexing rules, crawler permissions (e.g. GPTBot, PerplexityBot), and links your sitemap and llms.txt endpoints."
    },
    {
      q: "Does llms.txt improve ChatGPT ranking?",
      a: "Yes! AI crawlers use llms.txt to bypass bloated HTML navigation, scripts, and CSS, letting them read clean, structured text directly. This increases your chances of getting cited correctly in AI answers."
    }
  ];

  return (
    <div className={`min-h-screen font-sans transition-colors duration-300 antialiased ${!lightTheme ? "bg-cosmic-space bg-cosmic-grid text-white" : "bg-slate-50 text-slate-900"}`}>
      {/* TOP BANNER */}
      <div className="text-center py-3 px-6 bg-gradient-to-r from-emerald-900 via-indigo-900 to-emerald-900 text-white border-b border-emerald-700/50">
        <p className="text-sm font-bold tracking-wide flex items-center justify-center gap-2">
          <Sparkles className="w-4 h-4 text-emerald-300 animate-pulse" />
          <span>FREE AI UTILITY: Generate & Validate your /llms.txt and /agents.json files in seconds!</span>
        </p>
      </div>

      {/* HEADER */}
      <header className="sticky top-0 z-40 backdrop-blur-xl border-b border-border bg-surface/90">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="w-9 h-9 rounded-xl bg-accent p-0.5 shadow-lg group-hover:scale-105 transition-transform">
              <div className="w-full h-full rounded-lg bg-surface flex items-center justify-center">
                <Bot className="w-5 h-5 text-accent" />
              </div>
            </div>
            <div className="flex flex-col">
              <span className="font-heading font-extrabold text-lg tracking-tight">
                AI Scan <span className="text-accent font-black">My Site</span>
              </span>
              <span className="text-[10px] font-mono tracking-wider font-bold text-emerald-400">
                LLMS.TXT GENERATOR TOOL
              </span>
            </div>
          </Link>
          <div className="flex items-center gap-4">
            <Link href="/aeo-checker" className="text-sm font-bold text-ink-2 hover:text-ink transition-colors">
              AEO Checker
            </Link>
            <Link href="/geo-checker" className="text-sm font-bold text-ink-2 hover:text-ink transition-colors">
              GEO Checker
            </Link>
            <button
              onClick={() => setLightTheme(!lightTheme)}
              className="p-2 rounded-lg border border-border bg-surface-2 text-ink-2 hover:text-ink transition-colors"
            >
              {lightTheme ? <Moon className="w-4 h-4" /> : <Sun className="w-4 h-4" />}
            </button>
            <Link
              href="/"
              className="btn-primary text-xs px-4 py-2 font-bold flex items-center gap-1.5"
            >
              <Zap className="w-3.5 h-3.5" />
              <span>Full AI Audit</span>
            </Link>
          </div>
        </div>
      </header>

      {/* HERO SECTION */}
      <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pt-12 pb-12 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-mono font-bold mb-6 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400">
          <FileCode className="w-4 h-4" />
          <span>LLMS.TXT & AGENTS.JSON MANIFEST GENERATOR</span>
        </div>

        <h1 className="text-4xl sm:text-6xl font-heading font-extrabold tracking-tight leading-[1.15] mb-6">
          Free llms.txt Generator & <br />
          <span className="text-accent">AI Crawler Manifest Builder</span>
        </h1>

        <p className="text-lg sm:text-xl text-ink-2 max-w-3xl mx-auto leading-relaxed mb-10">
          Help ChatGPT, Gemini, Perplexity, and Claude index your platform cleanly. Generate your machine-readable <strong className="text-ink font-semibold">/llms.txt</strong> and <strong className="text-ink font-semibold">/agents.json</strong> files for instant download.
        </p>
      </section>

      {/* GENERATOR WORKSPACE */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* LEFT: INPUT CONTROLS */}
          <div className="card p-6 border border-border bg-surface flex flex-col gap-5">
            <h2 className="text-xl font-heading font-bold flex items-center gap-2">
              <Globe className="w-5 h-5 text-emerald-400" />
              <span>Website Information</span>
            </h2>

            <div>
              <label className="block text-xs font-mono uppercase text-ink-3 font-bold mb-2">Domain Name</label>
              <input
                type="text"
                value={domainInput}
                onChange={(e) => setDomainInput(e.target.value)}
                placeholder="e.g. yourwebsite.com"
                className="input w-full p-3 rounded-lg border border-border bg-surface-2 font-mono text-sm"
              />
            </div>

            <div>
              <label className="block text-xs font-mono uppercase text-ink-3 font-bold mb-2">Site Title</label>
              <input
                type="text"
                value={siteTitle}
                onChange={(e) => setSiteTitle(e.target.value)}
                placeholder="e.g. Acme Cloud Software"
                className="input w-full p-3 rounded-lg border border-border bg-surface-2 font-mono text-sm"
              />
            </div>

            <div>
              <label className="block text-xs font-mono uppercase text-ink-3 font-bold mb-2">Site Summary / Description</label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={3}
                placeholder="Describe your site for AI assistants..."
                className="input w-full p-3 rounded-lg border border-border bg-surface-2 font-mono text-sm"
              />
            </div>

            <div>
              <label className="block text-xs font-mono uppercase text-ink-3 font-bold mb-2">Core Sections & Links (Markdown)</label>
              <textarea
                value={keyLinks}
                onChange={(e) => setKeyLinks(e.target.value)}
                rows={5}
                placeholder="- [Title](url): description"
                className="input w-full p-3 rounded-lg border border-border bg-surface-2 font-mono text-sm"
              />
            </div>
          </div>

          {/* RIGHT: PREVIEW & DOWNLOAD */}
          <div className="flex flex-col gap-6">
            {/* LLMS.TXT PREVIEW */}
            <div className="card p-6 border border-border bg-surface flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-sm font-heading font-bold text-emerald-400 flex items-center gap-2">
                    <FileText className="w-4 h-4" />
                    <span>llms.txt Preview</span>
                  </span>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleCopy(generatedLlmsTxt, "llms")}
                      className="p-1.5 rounded bg-surface-2 hover:bg-surface border border-border text-xs font-mono flex items-center gap-1"
                    >
                      {copiedLlms ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copiedLlms ? "Copied!" : "Copy"}</span>
                    </button>
                    <button
                      onClick={() => handleDownload(generatedLlmsTxt, "llms.txt")}
                      className="p-1.5 rounded bg-emerald-500/20 text-emerald-400 hover:bg-emerald-500/30 border border-emerald-500/30 text-xs font-mono flex items-center gap-1 font-bold"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download</span>
                    </button>
                  </div>
                </div>
                <pre className="p-4 rounded-lg bg-surface-2 border border-border font-mono text-xs overflow-x-auto max-h-56 leading-relaxed text-ink-2">
                  {generatedLlmsTxt}
                </pre>
              </div>
            </div>

            {/* AGENTS.JSON PREVIEW */}
            <div className="card p-6 border border-border bg-surface flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-sm font-heading font-bold text-indigo-400 flex items-center gap-2">
                    <FileCode className="w-4 h-4" />
                    <span>agents.json Preview</span>
                  </span>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleCopy(generatedAgentsJson, "agents")}
                      className="p-1.5 rounded bg-surface-2 hover:bg-surface border border-border text-xs font-mono flex items-center gap-1"
                    >
                      {copiedAgents ? <Check className="w-3.5 h-3.5 text-indigo-400" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copiedAgents ? "Copied!" : "Copy"}</span>
                    </button>
                    <button
                      onClick={() => handleDownload(generatedAgentsJson, "agents.json")}
                      className="p-1.5 rounded bg-indigo-500/20 text-indigo-400 hover:bg-indigo-500/30 border border-indigo-500/30 text-xs font-mono flex items-center gap-1 font-bold"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download</span>
                    </button>
                  </div>
                </div>
                <pre className="p-4 rounded-lg bg-surface-2 border border-border font-mono text-xs overflow-x-auto max-h-52 leading-relaxed text-ink-2">
                  {generatedAgentsJson}
                </pre>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ SECTION */}
      <section className="py-16 border-t border-border bg-surface/30">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-heading font-extrabold mb-3">llms.txt FAQs</h2>
            <p className="text-ink-2">Common questions about machine-readable AI manifests.</p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="card border border-border overflow-hidden bg-surface">
                <button
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full p-5 text-left flex items-center justify-between font-bold text-lg text-ink"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-5 h-5 transition-transform ${openFaq === idx ? "rotate-180 text-emerald-400" : "text-ink-3"}`} />
                </button>
                {openFaq === idx && (
                  <div className="p-5 pt-0 text-sm text-ink-2 border-t border-border/50 bg-surface-2/30 leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="py-8 border-t border-border text-center text-xs text-ink-3 font-mono">
        <p>© {new Date().getFullYear()} AI Scan My Site — Free llms.txt & agents.json Generator Tool.</p>
      </footer>
    </div>
  );
}
